REGISTER_URL = "/auth/register"
LOGIN_URL = "/auth/login"
LOGOUT_URL = "/auth/logout"
GET_USER_URL = "/user/"
CHANGE_PASSWORD_URL = "/user/change_password"
CHANGE_NAME_URL = "/user/change_name"
CHANGE_EMAIL_URL = "/user/change_email"
