"""add uniq field

Revision ID: 1961c6ce7d4b
Revises: 2105cf88eb29
Create Date: 2024-03-14 20:49:34.802773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1961c6ce7d4b'
down_revision: Union[str, None] = '2105cf88eb29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_sign_ins_auth_token'), 'sign_ins', ['auth_token'])
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    op.create_unique_constraint(op.f('uq_users_name'), 'users', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_name'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_sign_ins_auth_token'), 'sign_ins', type_='unique')
    # ### end Alembic commands ###
